### ISSUE TITLE
Provider auth endpoint -> _complete_authz overwrite all passed cookies

### ISSUE THREAD

**Issue by ermakoves** [OpenIDC/pyoidc#501] opened 2018-03-01 08:56 UTC
https://github.com/OpenIDC/pyoidc/blob/3f21791df99aad8764b3ce796ba5689241ca86c4/src/oic/oauth2/provider.py#L711-L741

I think that the provider should return only those cookies that it changes or creates.
Maybe same logic exists in other endpoints

**Comment by schlenk** [comment] 2018-03-01 16:50
Looks like a duplicate of #398 ?

**Comment by tpazderka** [comment] 2019-02-07 21:44
Solved in #398

**Closed by tpazderka** 2019-02-07 21:44 UTC
