### ISSUE TITLE
Support multiple devices, single logout

### ISSUE THREAD

**Issue by ermakoves** [OpenIDC/pyoidc#439] opened 2017-11-17 09:48 UTC
I have 3-4 devaices and use one user for loggin. When i end session on some devaice, provider can delete session that not linked with user token

**Comment by lwm** [comment] 2017-11-18 11:22
Hi @ermakoves, can you please provide a more detailed description of your issue. A reproducible example would help. A failing test, if something is wrong in our code base is also really helpful too.

**Comment by ermakoves** [comment] 2017-11-20 08:22
https://github.com/OpenIDC/pyoidc/blob/master/src/oic/oic/provider.py#L598

You can't delete any sid. On one login you can have multiple sessions - like tablet, mobile and desktop. And logout on one devaice will delete first in sids lists, i think this is a bug.

**Comment by schlenk** [comment] 2017-11-20 18:54
So you have 3 User-Agents? One on Tablet, one on Mobile and one on Desktop? And all of those have logged in a RP for some user with the same UID?

The specification always talks just about a single User-Agent, so the case might be a bit surprising. The OIDC Session spec, section "5.  RP-Initiated Logout" talks about it like this.

>  At the logout endpoint, the OP SHOULD ask the End-User whether he wants to log out of the OP as well. If the End-User says "yes", then the OP MUST log out the End-User.

So technically it is correct to just pick any sid and kill the session, as the End-User gets logged out, and not some specific session. 

BUT you are correct that the code does a bad job at it. It only handles the case where a single user-agent is present, deletes the cookies for that one. And leaves other sessions orphaned in the sdb. This is harmless if only one authn cookie exists and only one user agent, as the session would be unreachable.
But another user agent may still have a valid cookie and depending on which sid gets deleted from the sdb there may be a session for the end user that survives the logout.

**Comment by ermakoves** [comment] 2017-11-21 09:49
> So you have 3 User-Agents? One on Tablet, one on Mobile and one on Desktop? And all of those have logged in a RP for some user with the same UID?

Yes. Yes. Yes

**Comment by lwm** [comment] 2017-11-21 10:07
Should you get motivated @ermakoves, we'd appreciate any PRs you might submit!

**Comment by schlenk** [comment] 2017-11-21 11:21
@lwm Shouldn't it be 'single logout' in the title? The login kind of works obviously, even if it isn't a 'single' login due to multiple user agents.

**Comment by lwm** [comment] 2017-11-21 18:38
Woops, fixed!

**Comment by tpazderka** [comment] 2019-01-14 20:15
Should be fixed by #585.

**Comment by tpazderka** [comment] 2019-02-16 10:12
This should be fixed on current master.

**Closed by tpazderka** 2019-02-16 10:12 UTC
Labels: enhancement
