### ISSUE TITLE
Whoever rewrote claims_match broke it!

### ISSUE THREAD

**Issue by rohe** [OpenIDC/pyoidc#335] opened 2017-04-25 14:57 UTC
The old version worked, the new doesn't.
Obviously the test coverage is incomplete.

**Comment by lwm** [comment] 2017-04-25 15:15
@rohe, we all want the code to work but such blunt language, erring on the side of blame isn't going to help the situation. Refactoring always brings the danger of breakage. We refactor with the hope of improving the maintenance for all.

This is an incomplete bug report. Please specify what isn't working and we can get to fixing it.

**Comment by rohe** [comment] 2017-04-25 17:56
My apologies. I had been searching for the bug for some days now.
Though it was in my test tool code but it wasn't. Very frustrating.
I will go back and provide a bug fix.

**Comment by Victor-Savu** [comment] 2017-05-27 06:56
Hi @rohe,
I was curious what the problem is with `claims_match`. Did you already find a solution for it?

**Comment by tpazderka** [comment] 2017-06-04 18:20
I think that this has been resolved. 
@rohe If that is indeed true, can you please close it?

**Comment by lwm** [comment] 2017-06-04 19:20
Yep, I saw that get merged. Closing :+1:

**Closed by lwm** 2017-06-04 19:20 UTC
