### ISSUE TITLE
ROPC Grant does not return id_token

### ISSUE THREAD

**Issue by MarcuStBogdan** [OpenIDC/pyoidc#617] opened 2019-02-25 08:34 UTC
Hi, 

If anyone can help me, i'm trying to get the id_token using the ROPC Grant flow. And even though i have set the response type to 'token id_token' i'm only receiving the token in the response. 

Below is the code of the rp:

        keys = [{
            "type": "RSA",
            "key": "../OP/keys/key.pem",
            "use": ["enc", "sig"]
        }]

        _, keyjar, _ = build_keyjar(keys)
        global client
        client = Client(verify_ssl=False, keyjar=keyjar, client_authn_method=CLIENT_AUTHN_METHOD)
        issuer_url = 'https://localhost'
        provider_info = client.provider_config(issuer_url)

        reg_info = {'application_type': 'web',
                    'application_name': 'Example RP',
                    'redirect_uris': ['https://127.0.0.1:5001/HybFlow'],
                    'grant_type': ['password'],
                    }

        client_reg = client.register(provider_info["registration_endpoint"], **reg_info)
        client.store_registration_info(client_reg)

        credentials = parse_qs(request.query_string.decode())
        request_args = {
            'grant_type': 'password',
            'client_id': client.client_id,
            'response_type': 'token id_token',
            'scope': ['openid', 'profile'],
            'state': state,
            'username': credentials['username'][0],
            'password': credentials['password'][0]
        }

        response = client.do_access_token_request(request=ROPCAccessTokenRequest,
                                             request_args=request_args,
                                             endpoint=client.token_endpoint,
                                             )

Thank you in advance for your help.

**Comment by tpazderka** [comment] 2019-02-25 20:43
This again looks like a miss in implementation. The `do_access_token_response` in `extension` is missing the part of the code that handles the needed `id_token` inclusion.

This might also be a result of refactoring/splitting the methods.

@rohe Can you please confirm?

**Comment by tpazderka** [comment] 2019-02-27 20:14
This is sort of "duplicate" for #615.

**Comment by tpazderka** [comment] 2019-03-06 19:16
Closing as a duplicate of #615. The ROPC will be fixed there.

**Closed by tpazderka** 2019-03-06 19:16 UTC
Labels: needs-confirmation
